version: '2'
services:
    factcheck-app:
        image: factcheck
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_DATA_MONGODB_URI=mongodb://factcheck-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=factcheck
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=internal
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=internal
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://factcheck-elasticsearch:9200
    factcheck-mongodb:
        extends:
            file: mongodb.yml
            service: factcheck-mongodb
    factcheck-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: factcheck-elasticsearch
    consul:
        image: consul:1.2.3
        command: consul agent -dev -ui -client 0.0.0.0
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600

    consul-config-loader:
        image: jhipster/consul-config-loader:v0.3.0
        volumes:
            - ./central-server-config:/config
        environment:
            - INIT_SLEEP_SECONDS=5
            - CONSUL_URL=consul
            - CONSUL_PORT=8500
        # Uncomment to load configuration into Consul from a Git repository
        # as configured in central-server-config/git2consul.json
        # Also set SPRING_CLOUD_CONSUL_CONFIG_FORMAT=files on your apps
        #    - CONFIG_MODE=git
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
